# Generated by Django 5.1.7 on 2025-03-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet_id',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
    ]
