# Generated by Django 5.1.7 on 2025-03-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Error', 'Error'), ('Debug', 'Debug'), ('Critical', 'Critical')], default='Info', max_length=10)),
                ('app', models.CharField(default='', max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Log entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
